name: Deploy to AKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build image
      run: |
        docker build -t my-flask-app .

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Push to ACR
      run: |
        az acr build --registry $ACR_NAME --image my-flask-app:${{ github.sha }} .
      env:
        ACR_NAME: mahdychprojects

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/my-flask-app my-flask-app=${ACR_NAME}.azurecr.io/my-flask-app:${{ github.sha }}
      env:
        ACR_NAME: mahdychprojects
